#!/usr/bin/env bash
git submodule update --init
cd jq
bundle install --binstubs=~/.local/bin --gemfile=docs/Gemfile --path=~/.gem
rm -rf docs/.bundle
autoreconf -i
./configure --prefix=${HOME}/.local
make
make install
make clean
if [[ -f config/ar-lib ]]; then
    rm config/ar-lib
fi
